version: '3.5'
name: authorization_service

services:
    web.facade:
        container_name: auth_webfacade
        image: auth_webfacade
        ports:
            - "5236:80"
        build: '../'
        environment:
            ConnectionStrings__DatabaseConnection: 'Data Source=auth_db; Initial Catalog=AuthorizationService; User ID=SA; Password=Adminadmin1@'
        depends_on:
            - db
        networks:
            - app_bridge_network
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: auth_db
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=y
            - MSSQL_SA_PASSWORD=Adminadmin1@

        networks:
            - app_bridge_network

networks:
    app_bridge_network:
        name: app_bridge_network
        driver: bridge
        external: true