version: '3.5'
name: authorization_service

services:
    web.facade:
        container_name: auth_webfacade
        image: auth_webfacade
        ports:
            - "5236:80"
        build: '../'
        environment:
            ConnectionStrings__DatabaseConnection: 'Data Source=mssql_server; Initial Catalog=AuthorizationService; User ID=SA; Password=Adminadmin1@'
            MailSettings__Password: ''
            CloudinarySettings__Cloud: ''
            CloudinarySettings__ApiKey: ''
            CloudinarySettings__ApiSecret: ''
        networks:
            - app_bridge_network

networks:
    app_bridge_network:
        name: app_bridge_network
        driver: bridge
        external: true